### ISSUE TITLE
About mingw-build-dep.sh  , better than mingw official dep ?

### ISSUE THREAD

**Issue by eromoe** [Jimmy-Z/aria2c1k#1]
Hello,
I find mingw-build.sh is enough to build, all dependencies can install by pacman.  Even `VER_EXPAT=2.2.2` is lower than `mingw64/mingw-w64-x86_64-expat 2.2.3-1`. So why use `mingw-build-dep.sh`  to install dep from source ?  Is this custom configuretion better than default ?

----------------

PS: I found error on

```
./mingw-build.sh: line 32: x86_64-w64-mingw32-strip: command not found
```

https://github.com/Jimmy-Z/aria2c1k/blob/505c1e2c726b07376d2faa9b037a94634c28ff45/mingw-build.sh#L32 

There is no `x86_64-w64-mingw32-strip` , so just `strip aria2c.exe && \` would work on msys2.

**Comment by Jimmy-Z** [comment]
`VER_EXPAT=2.2.2` because it's not updated in a while.

You're using MSYS2, this script works on Linux, they don't usually come with pre-built libraries.
