### ISSUE TITLE
failed to build on macOS

### ISSUE THREAD

**Issue by Ethan-yt** [Jimmy-Z/aria2c1k#2]
Hi!

I use homebrew to install mingw and run the script, then failed to build the zlib on macOS. Could you please provide a version of docker since there is an official DockerFile.

https://github.com/aria2/aria2/blob/master/Dockerfile.mingw

Thank you!

**Comment by Ethan-yt** [comment]
I have worked out a simple solution:

Modify the last RUN command to :
```
RUN git clone https://github.com/Jimmy-Z/aria2c1k.git && \
    git clone https://github.com/aria2/aria2 && \
    cd aria2 && patch -u -p1 < ../aria2c1k/c1k.patch && autoreconf -i && ./mingw-config && make && \
    $HOST-strip src/aria2c.exe
```

It works for me and should be the easiest way works for anyone who has trouble building this on another OS.

**Comment by Jimmy-Z** [comment]
Yeah, actually only the patch file is necessary, the rest are just some helper scripts I used, you can built it however you like, I'll update the README file.
